# Generated by Django 6.0.6 on 2026-08-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_item_previously_in'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='app_item_deleted_78c334_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['parent'], name='app_item_parent__2e9c68_idx'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deletion_reason',
        ),
    ]
