# Generated by Django 6.0.6 on 2026-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_item_deleted_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalbarcode",
            name="barcode_type",
            field=models.CharField(
                choices=[
                    ("UPC", "Manufacturer UPC"),
                    ("ORDER", "Purchase Order"),
                    ("SERIAL", "Serial Number"),
                    ("DISTRIBUTOR", "Distributor Part Number"),
                    ("SHIPPING", "Shipping Barcode"),
                    ("LCSC", "LCSC QR Code"),
                    ("OTHER", "Other"),
                ],
                default="UPC",
                help_text="Type of external barcode",
                max_length=50,
            ),
        ),
    ]
