# Generated by Django 6.0.6 on 2026-08-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_add_lcsc_qr_barcode_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemhistory',
            name='user',
        ),
    ]
