# Generated by Django 6.0.6 on 2026-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_itemhistory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("MOVE", "Move"),
                    ("CREATE", "Create"),
                    ("DELETE", "Delete"),
                    ("MERGE", "Merge"),
                    ("SPLIT", "Split"),
                    ("CLONE", "Clone"),
                    ("UPDATE", "Update"),
                    ("AUDIT", "Audit"),
                ],
                max_length=20,
            ),
        ),
    ]
