# Generated by Django 5.2.7 on 2025-10-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Common name for the item", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about the item"
                    ),
                ),
                (
                    "barcode_printed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item's barcode label was last printed",
                        null=True,
                    ),
                ),
                (
                    "contents_printed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the container's contents list was last printed (containers only)",
                        null=True,
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False, help_text="Whether this item has been deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When this item was deleted", null=True
                    ),
                ),
                (
                    "deletion_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for deletion (broken, consumed, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The item that this item is stored in",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="app.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="The external barcode value", max_length=255
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("UPC", "Manufacturer UPC"),
                            ("ORDER", "Purchase Order"),
                            ("SERIAL", "Serial Number"),
                            ("DISTRIBUTOR", "Distributor Part Number"),
                            ("OTHER", "Other"),
                        ],
                        default="UPC",
                        help_text="Type of external barcode",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context for this barcode association",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item this barcode is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_barcodes",
                        to="app.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("MOVED", "Moved"),
                            ("CREATED", "Created"),
                            ("DELETED", "Deleted"),
                            ("MERGED", "Merged"),
                            ("SPLIT", "Split"),
                            ("CLONED", "Cloned"),
                            ("UPDATED", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what changed"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data about the change",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="app.item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["deleted", "parent"], name="app_item_deleted_78c334_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["barcode_printed_at"], name="app_item_barcode_366b33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["contents_printed_at"], name="app_item_content_532e38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalbarcode",
            index=models.Index(fields=["code"], name="app_externa_code_c5ca8a_idx"),
        ),
        migrations.AddIndex(
            model_name="externalbarcode",
            index=models.Index(
                fields=["barcode_type"], name="app_externa_barcode_486552_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externalbarcode",
            unique_together={("code", "item")},
        ),
        migrations.AddIndex(
            model_name="itemhistory",
            index=models.Index(
                fields=["item", "timestamp"], name="app_itemhis_item_id_449180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemhistory",
            index=models.Index(
                fields=["action", "timestamp"], name="app_itemhis_action_c69858_idx"
            ),
        ),
    ]
